// Generated by gencpp from file nav_cctv/Locations.msg
// DO NOT EDIT!


#ifndef NAV_CCTV_MESSAGE_LOCATIONS_H
#define NAV_CCTV_MESSAGE_LOCATIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_cctv/Coordinate.h>

namespace nav_cctv
{
template <class ContainerAllocator>
struct Locations_
{
  typedef Locations_<ContainerAllocator> Type;

  Locations_()
    : msg_seq(0)
    , location()  {
    }
  Locations_(const ContainerAllocator& _alloc)
    : msg_seq(0)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _msg_seq_type;
  _msg_seq_type msg_seq;

   typedef std::vector< ::nav_cctv::Coordinate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_cctv::Coordinate_<ContainerAllocator> >::other >  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::nav_cctv::Locations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_cctv::Locations_<ContainerAllocator> const> ConstPtr;

}; // struct Locations_

typedef ::nav_cctv::Locations_<std::allocator<void> > Locations;

typedef boost::shared_ptr< ::nav_cctv::Locations > LocationsPtr;
typedef boost::shared_ptr< ::nav_cctv::Locations const> LocationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_cctv::Locations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_cctv::Locations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nav_cctv::Locations_<ContainerAllocator1> & lhs, const ::nav_cctv::Locations_<ContainerAllocator2> & rhs)
{
  return lhs.msg_seq == rhs.msg_seq &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nav_cctv::Locations_<ContainerAllocator1> & lhs, const ::nav_cctv::Locations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nav_cctv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nav_cctv::Locations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_cctv::Locations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_cctv::Locations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_cctv::Locations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_cctv::Locations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_cctv::Locations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_cctv::Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d39aba7ca00bf507fa36e8be0212b2bd";
  }

  static const char* value(const ::nav_cctv::Locations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd39aba7ca00bf507ULL;
  static const uint64_t static_value2 = 0xfa36e8be0212b2bdULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_cctv::Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_cctv/Locations";
  }

  static const char* value(const ::nav_cctv::Locations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_cctv::Locations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 msg_seq\n"
"Coordinate[] location\n"
"================================================================================\n"
"MSG: nav_cctv/Coordinate\n"
"int16 x\n"
"int16 y\n"
;
  }

  static const char* value(const ::nav_cctv::Locations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_cctv::Locations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_seq);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Locations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_cctv::Locations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_cctv::Locations_<ContainerAllocator>& v)
  {
    s << indent << "msg_seq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.msg_seq);
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_cctv::Coordinate_<ContainerAllocator> >::stream(s, indent + "    ", v.location[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_CCTV_MESSAGE_LOCATIONS_H
